language: rust
sudo: required
dist: trusty

cache:
  cargo: true

env:
  global:
    - OPENSSL_VERSION=openssl-1.0.2


before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

rust:
  - stable

before_script:
  - export PATH=$PATH:~/.cargo/bin
#  - rustup component add rustfmt-preview

script:
#  - cargo fmt --all -- --check
  - cargo build
  - cargo test
