[package]
name = "rjs"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ratel = "0.7.0"

[lib]
name = "rjs"
path = "src/lib.rs"
